### ISSUE TITLE
Enable a CircleCI build based on Python 3.12

### ISSUE THREAD

**Issue by wehs7661** [wehs7661/ensemble_md#53]
CircleCI builds based on Python 3.12 have been failing due to an error that seems related to some conflicts between Python 3.12 and `versioneer.py`, as shown below:
```
Processing /home/circleci/project
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /home/circleci/project/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/circleci/project/setup.py", line 30, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/circleci/project/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/home/circleci/project/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/circleci/project/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Exited with code exit status 1
```
An example failed build can be found for the the commit b9ba4785c1169da8c5858ede74c9f8cd7c066b60. Currently, we have left out settings for performing CI based on Python 3.12 for now, but will look into this more in the future.

**Comment by wehs7661** [comment]
Closing this issue now as the content will be copied over to #55 .
